
name: Boardgame

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn  package 

    - name: Upload a build artifact
      uses: actions/upload-artifact@v5.0.0
      with:
        name: boardgame-jar
        path: target/*jar
        
  security-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: 'nexus'   # This should match <id> in settings.xml
          settings-path: ${{ github.workspace }}
          
      - name: Trivy Installation
        run: |
         sudo apt-get install -y wget apt-transport-https gnupg lsb-release
         wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
         echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
         sudo apt-get update -y
         sudo apt-get install -y trivy
      - name: Trivy FS Scan
        run: trivy fs --exit-code 0 --severity HIGH,CRITICAL --format table -o fs-report.json .

      - name: Upload Trivy FS scan report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: fs-report.json


      - name: Gitleaks Installation
        run: sudo apt install gitleaks -y
      - name: Gitleaks Code Scan
        run: gitleaks detect --source . --report-path=gitleaks-report.json -f json 

  
      - name: Download a Build artifact
        uses: actions/download-artifact@v6.0.0
        with:
          name: boardgame-jar
          path: ./app
     
  
  builddeploy:

    runs-on: ubuntu-latest
    needs: security-check

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Download a Build artifact
      uses: actions/download-artifact@v6.0.0
      with:
        name: boardgame-jar
        path: ./app
      
    - name: Docker build and push
      uses: docker/login-action@v3.6.0
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Copy JAR to root for Docker build
      run: cp ./app/*.jar ./app.jar

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=hacked01/boardgame
        IMAGE_TAG=${GITHUB_SHA::7}  # Use first 7 chars of commit SHA
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG
       

    - name: Update deployment.yaml image
      run: |
       IMAGE_NAME=hacked01/boardgame
       DEPLOYMENT_FILE=deployment-service.yaml
       sed -i "s|image: .*|image: $IMAGE_NAME:$IMAGE_TAG|g" $DEPLOYMENT_FILE
       echo "Updated deployment.yaml:"
       cat $DEPLOYMENT_FILE

    - name: Commit and push updated deployment.yaml
      run: |
       git config user.name "github-actions"
       git config user.email "github-actions@github.com"
       git add deployment-service.yaml
       git commit -m "Update deployment image to $IMAGE_TAG"
       git push https://x-access-token:${GITHUB_TOKEN}@github.com/i-anuj/board-game.git HEAD:main

    - name: List running containers
      run: docker ps
